window.xlabVOC = [
  {id:"VOC-001",category:"产品信息 / Product information",theme:"车型层级清晰度 / Model hierarchy clarity",summary:"买家在选择车型前，需要用通俗方式对比 RS / AD / RT / GT / SP / ST。 / Buyers need a plain comparison of RS / AD / RT / GT / SP / ST before choosing a model.",persona:"终端用户、经销商 / End user, dealer",source:"公开 VOC 报告、官方产品线、媒体发布报道 / Public VOC report, official lineup, media launch coverage",observedDate:"2026-06-06",sentiment:"Concern",severity:"High",confidence:"High",owner:"Product",status:"Open",linkedRequirements:["FR-001","FR-002"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-002",category:"产品信息 / Product information",theme:"价格透明度 / Price transparency",summary:"高性价比会带来兴趣，也会让用户怀疑是否存在隐藏缩水。 / High spec-to-price ratio creates excitement, but also suspicion about hidden compromises.",persona:"终端用户、经销商 / End user, dealer",source:"公开 VOC 报告、Reddit 讨论、媒体评测 / Public VOC report, Reddit discussions, media reviews",observedDate:"2026-06-06",sentiment:"Mixed",severity:"Medium",confidence:"Medium",owner:"Content",status:"Open",linkedRequirements:["FR-003","FR-007"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-003",category:"适配与购买信心 / Fit and purchase confidence",theme:"尺码与 fit 不确定 / Sizing and fit uncertainty",summary:"用户和门店希望获得 fit 确认、几何说明和经销商辅助购买路径。 / Users and shops want fit confirmation, geometry explanation, and a dealer-assisted purchase path.",persona:"终端用户、经销商 / End user, dealer",source:"公开 VOC 报告、经销商/门店信号 / Public VOC report, dealer/shop signals",observedDate:"2026-06-06",sentiment:"Concern",severity:"High",confidence:"High",owner:"Product",status:"Open",linkedRequirements:["FR-004","FR-009","FR-029","FR-030"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-004",category:"零件与服务 / Parts and service",theme:"专有组件焦虑 / Proprietary component anxiety",summary:"一体把、垫圈、曲柄、功率计、轮组和座管系统会引发可维修性担忧。 / Cockpit, spacers, cranks, power meter, wheels, and seatpost systems create serviceability concerns.",persona:"终端用户、经销商、服务团队 / End user, dealer, service team",source:"公开 VOC 报告、MyBike.parts、Reddit 讨论 / Public VOC report, MyBike.parts, Reddit discussions",observedDate:"2026-06-06",sentiment:"Concern",severity:"High",confidence:"Medium-high",owner:"Service + Engineering",status:"Open",linkedRequirements:["FR-005","FR-020","FR-021","FR-022","FR-039"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-005",category:"产品信息 / Product information",theme:"配置版本对比 / Build variant comparison",summary:"用户会比较机械 105、Di2、GRX、Astana 版本、轮组、重量和价格跳跃。 / Users compare mechanical 105, Di2, GRX, Astana builds, wheels, weight, and price jumps.",persona:"终端用户、经销商 / End user, dealer",source:"公开 VOC 报告、媒体评测 / Public VOC report, media reviews",observedDate:"2026-06-06",sentiment:"Need",severity:"Medium",confidence:"Medium-high",owner:"Product",status:"Open",linkedRequirements:["FR-006"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-006",category:"购买渠道 / Purchase channel",theme:"经销商库存与配额清晰度 / Dealer inventory and allocation clarity",summary:"买家想知道哪里可以看车、试骑、下单、预留或维修。 / Buyers want to know where they can see, test, order, reserve, or service a bike.",persona:"终端用户、经销商 / End user, dealer",source:"公开 VOC 报告、经销商定位器、经销商页面 / Public VOC report, dealer locator, dealer pages",observedDate:"2026-06-06",sentiment:"Need",severity:"High",confidence:"High",owner:"B2B Ops",status:"Open",linkedRequirements:["FR-008","FR-010","FR-011","FR-012"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-007",category:"保修与售后 / Warranty and after-sales",theme:"保修规则清晰度 / Warranty clarity",summary:"终身保修是信任驱动因素，但注册时限和授权购买规则必须清楚。 / Lifetime warranty is a trust driver, but registration timing and authorized purchase rules must be clear.",persona:"终端用户、经销商、服务团队 / End user, dealer, service team",source:"官方保修、公开 VOC 报告 / Official warranty, public VOC report",observedDate:"2026-06-06",sentiment:"Need",severity:"High",confidence:"High",owner:"Service",status:"Open",linkedRequirements:["FR-016","FR-017","FR-018"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-008",category:"保修与售后 / Warranty and after-sales",theme:"退货政策焦虑 / Return policy anxiety",summary:"较短的线上退货窗口、补货费和运费责任会阻碍转化。 / Short online return windows, restocking fees, and shipping responsibility can block conversion.",persona:"终端用户 / End user",source:"官方退货政策、公开 VOC 报告 / Official return policy, public VOC report",observedDate:"2026-06-06",sentiment:"Concern",severity:"Medium",confidence:"High",owner:"Service + Content",status:"Open",linkedRequirements:["FR-019"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-009",category:"评价与社会证明 / Reviews and social proof",theme:"真实车主证明稀缺 / Owner proof scarcity",summary:"全球上市时间较短，真实购后反馈仍然稀缺。 / Authentic post-purchase feedback is sparse because the global launch wave is recent.",persona:"终端用户、产品团队 / End user, product team",source:"公开 VOC 报告、车主讨论串 / Public VOC report, owner threads",observedDate:"2026-06-06",sentiment:"Need",severity:"Medium-high",confidence:"Medium-high",owner:"Product",status:"Open",linkedRequirements:["FR-023","FR-025"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-010",category:"评价与社会证明 / Reviews and social proof",theme:"媒体评测分散 / Media review dispersion",summary:"第三方评测已经存在，但分散在不同媒体站点和产品类别里。 / Third-party reviews exist but are spread across media sites and product categories.",persona:"终端用户、内容团队 / End user, content team",source:"Cyclingnews、Velo、Bikerumor、公开 VOC 报告 / Cyclingnews, Velo, Bikerumor, public VOC report",observedDate:"2026-06-06",sentiment:"Need",severity:"Medium",confidence:"Medium-high",owner:"Content",status:"Open",linkedRequirements:["FR-024"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-011",category:"品牌信任 / Brand trust",theme:"XDS 制造可信度 / XDS manufacturing credibility",summary:"尽管 XDS 具备制造规模和垂直整合能力，西方市场的品牌认知仍较低。 / Western brand awareness is low despite XDS manufacturing scale and vertical integration.",persona:"终端用户、经销商、代理商 / End user, dealer, distributor",source:"官方网站、PRNewswire、公开 VOC 报告 / Official site, PRNewswire, public VOC report",observedDate:"2026-06-06",sentiment:"Concern",severity:"High",confidence:"High",owner:"Content + Design",status:"Open",linkedRequirements:["FR-026","FR-028"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-012",category:"品牌信任 / Brand trust",theme:"WorldTour 合法性背书 / WorldTour legitimacy",summary:"XDS-Astana 背书能帮助公路车买家认为 X-LAB 足够专业，但证明需要容易找到。 / XDS-Astana association helps road buyers see X-LAB as serious, but proof needs to be easy to find.",persona:"终端用户、经销商 / End user, dealer",source:"媒体评测、赛事报道、公开 VOC 报告 / Media reviews, race coverage, public VOC report",observedDate:"2026-06-06",sentiment:"Positive",severity:"Medium",confidence:"Medium-high",owner:"Content",status:"Open",linkedRequirements:["FR-027"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-013",category:"电助力支持 / E-bike support",theme:"电机、电池、App 与合规 / Motor, battery, app, compliance",summary:"城市和电助力买家关注电池、电机、App 支持、本地服务和法规等级。 / Urban and e-bike buyers care about battery, motor, app support, local service, and class compliance.",persona:"终端用户、服务团队 / End user, service team",source:"Bikerumor 电助力评测、公开 VOC 报告 / Bikerumor e-bike review, public VOC report",observedDate:"2026-06-06",sentiment:"Need",severity:"Medium",confidence:"Medium",owner:"Service + Product",status:"Open",linkedRequirements:["FR-031","FR-032"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-014",category:"经销商赋能 / Dealer enablement",theme:"经销商服务手册 / Dealer service playbook",summary:"经销商需要官方支持来回答服务、兼容、异议、保修、尺码和零件问题。 / Dealers need official support for service, compatibility, objections, warranty, sizing, and parts answers.",persona:"经销商、服务团队 / Dealer, service team",source:"经销商/门店信号、公开 VOC 报告 / Dealer/shop signals, public VOC report",observedDate:"2026-06-06",sentiment:"Need",severity:"Medium",confidence:"Medium",owner:"Service + Content",status:"Open",linkedRequirements:["FR-013","FR-014"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-015",category:"经销商赋能 / Dealer enablement",theme:"线索响应速度 / Lead response speed",summary:"经销商转化依赖对 RFQ、试骑和车辆预留线索的快速响应。 / Dealer conversion depends on fast response to RFQ, test ride, and reserve-bike leads.",persona:"经销商、销售运营 / Dealer, sales ops",source:"经销商渠道分析、公开 VOC 报告 / Dealer channel analysis, public VOC report",observedDate:"2026-06-06",sentiment:"Need",severity:"Medium",confidence:"Medium",owner:"B2B Ops",status:"Open",linkedRequirements:["FR-015"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-016",category:"供应商与代理商 / Supplier and distributor",theme:"合作伙伴路径清晰度 / Partner path clarity",summary:"全球代理商已经存在，但经销商、代理商和供应商的联系路径需要更清晰。 / Global distributors exist, but dealer, distributor, and supplier contact paths need clearer routing.",persona:"代理商、供应商、经销商 / Distributor, supplier, dealer",source:"官方代理商列表、公开 VOC 报告 / Official distributor list, public VOC report",observedDate:"2026-06-06",sentiment:"Need",severity:"Medium",confidence:"Medium-high",owner:"Sales Ops",status:"Open",linkedRequirements:["FR-037","FR-038"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-017",category:"零件与服务 / Parts and service",theme:"零件可用性信心 / Parts availability confidence",summary:"备件可用性和保修周转速度将决定早期热情能否转化为忠诚。 / Spare-parts availability and warranty turnaround will decide whether early enthusiasm becomes loyalty.",persona:"经销商、服务团队、终端用户 / Dealer, service team, end user",source:"经销商风险分析、公开 VOC 报告 / Dealer risk analysis, public VOC report",observedDate:"2026-06-06",sentiment:"Concern",severity:"Medium-high",confidence:"Medium",owner:"Supplier Ops",status:"Open",linkedRequirements:["FR-039"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-018",category:"数据分析 / Analytics",theme:"转化摩擦度量 / Conversion friction measurement",summary:"产品信息缺口和渠道摩擦应被记录为转化事件。 / Product information gaps and channel friction should be measured as conversion events.",persona:"产品团队、数据分析 / Product team, analytics",source:"需求洞察建议 / Demand intelligence recommendations",observedDate:"2026-06-06",sentiment:"Need",severity:"Medium",confidence:"Medium",owner:"Analytics",status:"Open",linkedRequirements:["FR-040"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-019",category:"需求管理 / Demand management",theme:"证据数据库与追溯 / Evidence database and traceability",summary:"需求需要记录来源、日期、画像、严重度、置信度、负责人、关联需求追溯，并在转需求前经过评分门禁。 / Requirements need source, date, persona, severity, confidence, owner, linked requirement traceability, and a scored review gate before demand conversion.",persona:"产品团队 / Product team",source:"需求洞察建议 / Demand intelligence recommendations",observedDate:"2026-06-06",sentiment:"Need",severity:"High",confidence:"High",owner:"Product",status:"In progress",linkedRequirements:["FR-033","FR-034","FR-036","FR-044","FR-048"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-020",category:"需求管理 / Demand management",theme:"月度 VOC 刷新 / Monthly VOC refresh",summary:"上市初期市场情绪变化很快，因此 VOC 必须按月刷新。 / The launch wave is fresh, so VOC must be refreshed monthly while market sentiment changes quickly.",persona:"产品团队、内容团队 / Product team, content team",source:"需求洞察建议 / Demand intelligence recommendations",observedDate:"2026-06-06",sentiment:"Need",severity:"Medium",confidence:"Medium",owner:"Product",status:"Open",linkedRequirements:["FR-035"],evidence:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"VOC-021",category:"治理 / Governance",theme:"强制变更记录 / Mandatory change logging",summary:"所有页面、模块、区块、组件、文案、流程和数据改动都必须进入需求清单。 / All page, module, section, component, copy, flow, and data changes must enter the requirement list.",persona:"项目负责人、产品团队 / Project owner, product team",source:"用户治理要求 / User governance request",observedDate:"2026-06-06",sentiment:"Directive",severity:"High",confidence:"High",owner:"Product",status:"Active",linkedRequirements:["FR-041"],evidence:"reports/x-lab-ui-ux-common-requirements.md"},
  {id:"VOC-022",category:"需求管理 / Demand management",theme:"需求表格偏好 / Requirement table preference",summary:"需求清单应作为密集总览表维护，而不是卡片或看板；管理导航放在左侧并支持收拢；reset 操作紧凑并与筛选同排；收拢菜单显示英文短词；VOC 转需求需要评分评审；Boss 需求分类最高优先级；侧栏收拢展开只用左侧图标；所有需求按开发月份、MVP 阶段和月度 deadline 规划；设计系统需要可视化页面并与 design.md 和 edit log 定期同步；需求信息和 VOC 信息都应存入 Notion 数据库，并与本地总览页面保持同步。 / The requirement list should be maintained as a dense table overview, not as cards or a board; management navigation should sit on the left and support collapse; reset actions should stay compact and aligned with filters; collapsed menu labels should show one English word; VOC conversion needs scored review before becoming requirements; Boss requirements need a highest-priority classification; sidebar collapse and expand should use a left-side icon only; all requirements should be planned by development month with MVP phase and monthly deadline; design system needs a visual page in the menu, synced periodically with design.md and edit log; requirement information and VOC information should be stored in Notion databases and kept in sync with the local overview pages.",persona:"项目负责人、产品团队 / Project owner, product team",source:"用户 UI 反馈 / User UI feedback",observedDate:"2026-06-06",sentiment:"Directive",severity:"High",confidence:"High",owner:"Product + Design",status:"Active",linkedRequirements:["FR-042","FR-045","FR-046","FR-047","FR-048","FR-049","FR-050","FR-051","FR-052","FR-053","FR-054","FR-055"],evidence:"requirements-board.html"},
  {id:"VOC-023",category:"文档治理 / Documentation governance",theme:"Markdown 唯一性与双语输出 / Markdown uniqueness and bilingual output",summary:"Markdown 文档必须按类型唯一、双语、包含修改记录，并同步到 Notion。 / Markdown documents must be unique by type, bilingual, include change logs, and sync to Notion.",persona:"项目负责人、内容团队 / Project owner, content team",source:"用户治理要求 / User governance request",observedDate:"2026-06-06",sentiment:"Directive",severity:"High",confidence:"High",owner:"Content + Product",status:"Active",linkedRequirements:["FR-043"],evidence:"reports/x-lab-ui-ux-common-requirements.md"}
];

window.xlabVOCReviewDimensions = [
  {key:"evidence",label:"Evidence",weight:25,description:"Source reliability, freshness and traceability"},
  {key:"impact",label:"Impact",weight:25,description:"Business, trust, conversion or operational impact"},
  {key:"reach",label:"Reach",weight:20,description:"Persona breadth and affected user coverage"},
  {key:"urgency",label:"Urgency",weight:15,description:"Time sensitivity and current execution pressure"},
  {key:"fit",label:"Fit",weight:15,description:"Alignment with X-LAB website and management goals"}
];

function xlabVOCScoreValue(value, scale) {
  return scale[value] ?? scale.default ?? 0;
}

function xlabReviewVOC(item) {
  const confidenceScore = xlabVOCScoreValue(item.confidence, {"High":25,"Medium-high":21,"Medium":17,"Low":8,default:14});
  const severityScore = xlabVOCScoreValue(item.severity, {"High":25,"Medium-high":21,"Medium":16,"Low":8,default:14});
  const personaCount = item.persona.split(",").length;
  const reachScore = Math.min(20, 8 + personaCount * 4 + (item.persona.includes("dealer") || item.persona.includes("Dealer") ? 4 : 0));
  const urgencyScore = item.sentiment === "Directive" || item.severity === "High" ? 15 : item.severity === "Medium-high" ? 12 : 9;
  const governanceCategory = ["Demand management","Governance","Documentation governance"].some((category) => item.category.includes(category));
  const fitScore = governanceCategory ? 15 : item.linkedRequirements.length > 1 ? 13 : 11;
  const dimensions = {evidence:confidenceScore,impact:severityScore,reach:reachScore,urgency:urgencyScore,fit:fitScore};
  const score = Object.values(dimensions).reduce((sum, value) => sum + value, 0);
  return {
    dimensions,
    score,
    gate: score > 60 ? "Pass" : "Hold",
    decision: score > 60 ? "Enter requirement list" : "Keep in VOC review",
    threshold: 60
  };
}

window.xlabVOC.forEach((item) => {
  item.review = xlabReviewVOC(item);
});

window.xlabRequirements = [
  {id:"FR-001",priority:"P0",module:"Product discovery",requirement:"Model comparison matrix / 车型对比矩阵",vocIds:["VOC-001"],requestDate:"2026-06-06",plannedDate:"2026-06-21",status:"Triage",owner:"Product",scope:"Product pages, model comparison",acceptance:"Compare active models by use case, price, weight, spec, warranty and channel availability.",validation:"Not tested",files:"model-comparison.html"},
  {id:"FR-002",priority:"P0",module:"Product discovery",requirement:"Plain-language model selector / 白话版车型选择器",vocIds:["VOC-001"],requestDate:"2026-06-06",plannedDate:"2026-06-23",status:"Planned",owner:"Product",scope:"Bike finder, product discovery",acceptance:"Ask riding type, budget, terrain, fit priority and performance goal, then recommend 2-3 models.",validation:"Not tested",files:"bike-finder.html"},
  {id:"FR-003",priority:"P0",module:"Product detail",requirement:"Spec transparency block / 参数透明模块",vocIds:["VOC-002"],requestDate:"2026-06-06",plannedDate:"2026-06-25",status:"Backlog",owner:"Product",scope:"Product detail pages",acceptance:"Show full component list, frame material, wheels, drivetrain, cockpit, power meter, tire clearance and weight basis.",validation:"Not tested",files:"bike-ad9.html"},
  {id:"FR-004",priority:"P0",module:"Product detail",requirement:"Geometry and fit explainer / 几何与适配说明",vocIds:["VOC-003"],requestDate:"2026-06-06",plannedDate:"2026-06-24",status:"Build",owner:"Design + Engineering",scope:"Product detail, custom bike, dealer fit",acceptance:"Show geometry chart, size calculator, height/inseam guidance and dealer fit confirmation.",validation:"Partial source inspection",files:"custom-bike.html, bike-ad9.html"},
  {id:"FR-005",priority:"P1",module:"Product detail",requirement:"Integrated cockpit configuration guide / 一体把与座舱配置指南",vocIds:["VOC-004"],requestDate:"2026-06-06",plannedDate:"2026-07-02",status:"Partial",owner:"Product + Service",scope:"Product detail, custom bike",acceptance:"Explain cockpit sizes, adjustment range, replacement route and purchase-time change rules.",validation:"Partial source inspection",files:"custom-bike.html"},
  {id:"FR-006",priority:"P1",module:"Product detail",requirement:"Build variant comparison / 配置版本对比",vocIds:["VOC-005"],requestDate:"2026-06-06",plannedDate:"2026-07-04",status:"Backlog",owner:"Product",scope:"Product detail, model comparison",acceptance:"Compare variants by price, groupset, wheels, power meter, weight and target rider.",validation:"Not tested",files:"bike-ad9.html, model-comparison.html"},
  {id:"FR-007",priority:"P1",module:"Product detail",requirement:"Why this price FAQ / 为什么这个价格 FAQ",vocIds:["VOC-002"],requestDate:"2026-06-06",plannedDate:"2026-07-03",status:"Partial",owner:"Content",scope:"Brand and product pages",acceptance:"Explain vertical integration, dealer model, manufacturing background, warranty and service commitments.",validation:"Partial source inspection",files:"index.html, factory.html, bike-ad9.html"},
  {id:"FR-008",priority:"P0",module:"Dealer channel",requirement:"Dealer locator with inventory / 经销商库存定位器",vocIds:["VOC-006"],requestDate:"2026-06-06",plannedDate:"2026-06-28",status:"Triage",owner:"B2B Ops",scope:"Stores, dealer data, local inventory",acceptance:"Show location, service capability, available models/sizes, test ride status and inventory timestamp.",validation:"Not tested",files:"stores.html, local-inventory.html"},
  {id:"FR-009",priority:"P0",module:"Dealer channel",requirement:"Reserve or request test ride flow / 试骑预约与车辆预留流程",vocIds:["VOC-003"],requestDate:"2026-06-06",plannedDate:"2026-06-29",status:"Partial",owner:"B2B Ops",scope:"Stores, dealer leads",acceptance:"User can request test ride or reserve bike; dealer receives model, size, time, contact and notes.",validation:"Not tested",files:"stores.html, store-pickup.html"},
  {id:"FR-010",priority:"P0",module:"Dealer channel",requirement:"Allocation and lead-time visibility / 配额与交期可视化",vocIds:["VOC-006"],requestDate:"2026-06-06",plannedDate:"2026-06-30",status:"Partial",owner:"Sales Ops",scope:"Product pages, dealer pages, B2B dashboard",acceptance:"Show lead time, preorder status, allocation batch, deposit rules and dealer contact path.",validation:"Partial source inspection",files:"dealers.html, b2b-dashboard.html"},
  {id:"FR-011",priority:"P1",module:"Dealer channel",requirement:"Dealer detail page / 经销商详情页",vocIds:["VOC-006"],requestDate:"2026-06-06",plannedDate:"2026-07-08",status:"Backlog",owner:"B2B Ops",scope:"Dealer profiles",acceptance:"Each dealer page shows address, services, supported categories, certification, appointments and warranty capability.",validation:"Not tested",files:"dealers.html"},
  {id:"FR-012",priority:"P0",module:"Dealer portal",requirement:"Dealer inventory management / 经销商库存管理",vocIds:["VOC-006"],requestDate:"2026-06-06",plannedDate:"2026-07-01",status:"Partial",owner:"B2B Ops",scope:"Dealer portal, inventory sync",acceptance:"Dealers update stock by model, size, color, test-bike status, preorder quantity and lead time.",validation:"Partial source inspection",files:"b2b-dashboard.html, local-inventory.html"},
  {id:"FR-013",priority:"P1",module:"Dealer portal",requirement:"Dealer service playbook library / 经销商服务手册库",vocIds:["VOC-014"],requestDate:"2026-06-06",plannedDate:"2026-07-09",status:"Backlog",owner:"Service",scope:"Dealer training, technical docs",acceptance:"Portal contains manuals, compatibility docs, warranty workflow, escalation contacts and training videos.",validation:"Not tested",files:"dealer-training.html, technical-documents.html"},
  {id:"FR-014",priority:"P1",module:"Dealer portal",requirement:"Dealer objection-handling sheet / 经销商异议处理单页",vocIds:["VOC-014"],requestDate:"2026-06-06",plannedDate:"2026-07-10",status:"Backlog",owner:"Content",scope:"Dealer sales enablement",acceptance:"Dealer can download or share one-page sales support material with approved answers.",validation:"Not tested",files:"dealer-training.html, launch-assets.html"},
  {id:"FR-015",priority:"P1",module:"Dealer portal",requirement:"Lead inbox for RFQ/test rides / RFQ 与试骑线索收件箱",vocIds:["VOC-015"],requestDate:"2026-06-06",plannedDate:"2026-07-05",status:"In design",owner:"B2B Ops",scope:"Dealer portal, RFQ, test ride",acceptance:"Show incoming leads, source page, requested model/size, status, owner, SLA and next action.",validation:"Not tested",files:"b2b-dashboard.html, rfq-orders.html"},
  {id:"FR-016",priority:"P0",module:"Warranty",requirement:"Warranty registration flow / 保修注册流程",vocIds:["VOC-007"],requestDate:"2026-06-06",plannedDate:"2026-06-30",status:"Planned",owner:"Service",scope:"Owner support",acceptance:"User registers within 90 days using serial number, proof, dealer, model, size and contact info.",validation:"Not tested",files:"product-registration.html"},
  {id:"FR-017",priority:"P0",module:"Warranty",requirement:"Warranty explainer page / 保修说明页",vocIds:["VOC-007"],requestDate:"2026-06-06",plannedDate:"2026-07-01",status:"Backlog",owner:"Service + Content",scope:"Support pages",acceptance:"Explain frame, wheel, owner, authorized purchase, registration deadline, exclusions and claim steps.",validation:"Not tested",files:"warranty-claim.html"},
  {id:"FR-018",priority:"P1",module:"Warranty",requirement:"Warranty claim tracking / 保修理赔追踪",vocIds:["VOC-007"],requestDate:"2026-06-06",plannedDate:"2026-07-08",status:"Build",owner:"Service",scope:"Support and B2B dashboard",acceptance:"User/dealer submits claim, uploads photos/docs, gets case ID, tracks status and next action.",validation:"Not tested",files:"warranty-claim.html, b2b-dashboard.html"},
  {id:"FR-019",priority:"P1",module:"Warranty",requirement:"Return policy decision guide / 退货政策决策指南",vocIds:["VOC-008"],requestDate:"2026-06-06",plannedDate:"2026-07-11",status:"Backlog",owner:"Service + Content",scope:"Checkout and support",acceptance:"Explain return window, restocking fee, ridden-bike rules, shipping responsibility and dealer-vs-online differences.",validation:"Not tested",files:"warranty-claim.html"},
  {id:"FR-020",priority:"P0",module:"Parts and compatibility",requirement:"Compatibility and spare-parts database / 兼容性与备件数据库",vocIds:["VOC-004"],requestDate:"2026-06-06",plannedDate:"2026-07-03",status:"Planned",owner:"Service + Engineering",scope:"Technical docs, parts support",acceptance:"Search by model/year/component and show part numbers, alternatives, availability, service notes and replacement route.",validation:"Not tested",files:"technical-documents.html"},
  {id:"FR-021",priority:"P1",module:"Parts and compatibility",requirement:"Proprietary component transparency badges / 专有零件透明标签",vocIds:["VOC-004"],requestDate:"2026-06-06",plannedDate:"2026-07-12",status:"Backlog",owner:"Product",scope:"Product/spec pages",acceptance:"Label component type and explain service impact and replacement availability.",validation:"Not tested",files:"bike-ad9.html, technical-documents.html"},
  {id:"FR-022",priority:"P1",module:"Parts and compatibility",requirement:"Chainring and drivetrain compatibility guide / 盘片与传动兼容指南",vocIds:["VOC-004"],requestDate:"2026-06-06",plannedDate:"2026-07-13",status:"Backlog",owner:"Service",scope:"Technical documents",acceptance:"Show supported chainring sizes, interface/BCD, drivetrain limits, terrain advice and dealer service guide.",validation:"Not tested",files:"technical-documents.html"},
  {id:"FR-023",priority:"P1",module:"Reviews and social proof",requirement:"Verified owner review system / 认证车主评价系统",vocIds:["VOC-009"],requestDate:"2026-06-06",plannedDate:"2026-07-15",status:"Backlog",owner:"Product",scope:"Owner garage, reviews",acceptance:"Owners submit verified reviews tied to serial/order/dealer and filter by model, size, terrain and ownership time.",validation:"Not tested",files:"owner-garage.html"},
  {id:"FR-024",priority:"P1",module:"Reviews and social proof",requirement:"Media review hub / 媒体评测中心",vocIds:["VOC-010"],requestDate:"2026-06-06",plannedDate:"2026-07-14",status:"Backlog",owner:"Content",scope:"Brand and product pages",acceptance:"Aggregate third-party reviews with date, model, publication, takeaway and outbound link.",validation:"Not tested",files:"race-validation.html, bike-ad9.html"},
  {id:"FR-025",priority:"P2",module:"Reviews and social proof",requirement:"Real owner follow-up survey / 真实车主跟进调研",vocIds:["VOC-009"],requestDate:"2026-06-06",plannedDate:"2026-07-25",status:"Backlog",owner:"Product",scope:"Owner garage, VOC database",acceptance:"Send surveys at 14, 60 and 180 days and feed responses into VOC database.",validation:"Not tested",files:"owner-garage.html"},
  {id:"FR-026",priority:"P0",module:"Brand trust",requirement:"XDS manufacturing credibility page / XDS 制造可信度页面",vocIds:["VOC-011"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Released",owner:"Content + Design",scope:"Factory and homepage",acceptance:"Explain XDS history, manufacturing scale, vertical integration, quality controls, racing and dealer support.",validation:"Source verified",files:"factory.html, index.html"},
  {id:"FR-027",priority:"P1",module:"Brand trust",requirement:"WorldTour and race proof page / WorldTour 与赛事背书页面",vocIds:["VOC-012"],requestDate:"2026-06-06",plannedDate:"2026-07-06",status:"Planned",owner:"Content",scope:"Race validation",acceptance:"Show race program, bikes used, team/athlete proof, technology transfer and media coverage.",validation:"Not tested",files:"race-validation.html"},
  {id:"FR-028",priority:"P1",module:"Brand trust",requirement:"Brand comparison narrative / 品牌对比叙事",vocIds:["VOC-011"],requestDate:"2026-06-06",plannedDate:"2026-07-16",status:"Backlog",owner:"Content + Product",scope:"Brand and product pages",acceptance:"Explain positioning by value, dealer support, warranty, specs and use case without unsupported claims.",validation:"Not tested",files:"index.html, bike-ad9.html"},
  {id:"FR-029",priority:"P1",module:"Checkout",requirement:"Pre-purchase confidence checklist / 购买前信心检查清单",vocIds:["VOC-003"],requestDate:"2026-06-06",plannedDate:"2026-07-09",status:"Partial",owner:"Product",scope:"Custom bike, checkout support",acceptance:"Confirm size confidence, local service path, warranty registration, return terms and configuration before checkout.",validation:"Partial source inspection",files:"custom-bike.html, stores.html"},
  {id:"FR-030",priority:"P1",module:"Checkout",requirement:"Dealer-assisted checkout option / 经销商辅助结账选项",vocIds:["VOC-003"],requestDate:"2026-06-06",plannedDate:"2026-07-10",status:"Partial",owner:"Sales Ops",scope:"Checkout, store pickup",acceptance:"User can choose ship-to-dealer, dealer pickup, dealer assembly or dealer consultation where available.",validation:"Partial source inspection",files:"store-pickup.html, custom-bike.html"},
  {id:"FR-031",priority:"P2",module:"E-bike support",requirement:"E-bike service and compliance center / 电助力服务与合规中心",vocIds:["VOC-013"],requestDate:"2026-06-06",plannedDate:"2026-07-28",status:"Backlog",owner:"Service + Product",scope:"E-bike support",acceptance:"Show motor/battery specs, range basis, charging, replacement path, app support, class compliance and local service.",validation:"Not tested",files:"technical-documents.html"},
  {id:"FR-032",priority:"P2",module:"E-bike support",requirement:"Battery and motor support ticket type / 电池与电机专用工单类型",vocIds:["VOC-013"],requestDate:"2026-06-06",plannedDate:"2026-07-29",status:"Backlog",owner:"Service",scope:"Support forms",acceptance:"Capture motor, battery serial, firmware/app version, range issue, error code, charger status and safety notes.",validation:"Not tested",files:"warranty-claim.html"},
  {id:"FR-033",priority:"P0",module:"Demand management",requirement:"VOC evidence database / VOC 证据数据库",vocIds:["VOC-019"],requestDate:"2026-06-06",plannedDate:"2026-07-02",status:"Partial",owner:"Product",scope:"VOC and demand records",acceptance:"Record VOC item, source, observed date, user type, product line, sentiment, severity, confidence, owner and linked requirements.",validation:"Partial documentation verified",files:"voc-list.html, reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"FR-034",priority:"P0",module:"Demand management",requirement:"Requirement intake board / 需求 intake 看板",vocIds:["VOC-019"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Ready",owner:"Product",scope:"Requirement overview",acceptance:"Maintain requirements in one table with priority, owner, dates, VOC and validation state.",validation:"Source verified",files:"requirements-board.html"},
  {id:"FR-035",priority:"P1",module:"Demand management",requirement:"Monthly VOC refresh workflow / 月度 VOC 刷新流程",vocIds:["VOC-020"],requestDate:"2026-06-06",plannedDate:"2026-07-20",status:"Backlog",owner:"Product",scope:"VOC refresh and reports",acceptance:"Store refresh notes, new sources, sentiment changes, new risks, resolved concerns and priority changes.",validation:"Not tested",files:"reports/x-lab-voc-demand-intelligence-2026-06-06.md"},
  {id:"FR-036",priority:"P1",module:"Demand management",requirement:"Evidence-to-feature traceability / 证据到功能的追溯",vocIds:["VOC-019"],requestDate:"2026-06-06",plannedDate:"2026-07-18",status:"Partial",owner:"Product",scope:"Requirement records, VOC links",acceptance:"Each functional requirement links to one or more VOC evidence items with confidence and last verified date.",validation:"Partial documentation verified",files:"requirements-board.html, voc-list.html, reports/*.md"},
  {id:"FR-037",priority:"P1",module:"Supplier and distributor",requirement:"Distributor directory and inquiry flow / 代理商目录与询价流程",vocIds:["VOC-016"],requestDate:"2026-06-06",plannedDate:"2026-07-17",status:"Backlog",owner:"Sales Ops",scope:"Dealer and distributor pages",acceptance:"List distributors by country/region with contact method, category support, dealer application path and escalation contact.",validation:"Not tested",files:"dealers.html, supplier.html"},
  {id:"FR-038",priority:"P1",module:"Supplier and distributor",requirement:"Supplier capability intake form / 供应商能力准入表单",vocIds:["VOC-016"],requestDate:"2026-06-06",plannedDate:"2026-07-12",status:"Partial",owner:"Supplier Ops",scope:"Supplier route and B2B login",acceptance:"Potential suppliers submit company profile, category, certifications, capacity, region, sample availability, compliance docs and contact.",validation:"Partial source inspection",files:"supplier.html, supplier-login.html"},
  {id:"FR-039",priority:"P2",module:"Supplier and distributor",requirement:"Parts availability dashboard / 零件可用性仪表盘",vocIds:["VOC-004","VOC-017"],requestDate:"2026-06-06",plannedDate:"2026-07-26",status:"Partial",owner:"Supplier Ops",scope:"B2B dashboard, service parts",acceptance:"Internal users view proprietary parts stock, lead time, regional stock, backorders and critical part alerts.",validation:"Partial source inspection",files:"b2b-dashboard.html, technical-documents.html"},
  {id:"FR-040",priority:"P1",module:"Analytics",requirement:"Conversion friction analytics / 转化摩擦分析",vocIds:["VOC-018"],requestDate:"2026-06-06",plannedDate:"2026-07-19",status:"Backlog",owner:"Analytics",scope:"Website and portal events",acceptance:"Track comparison usage, size calculator, dealer locator clicks, test ride requests, warranty visits, compatibility search and checkout abandonment.",validation:"Not tested",files:"app.js"},
  {id:"FR-041",priority:"P0",module:"Demand management",requirement:"Mandatory change logging gate / 改动记录强制门禁",vocIds:["VOC-021"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Active",owner:"Product",scope:"All project changes",acceptance:"Every change has requirement object, reason, scope, priority, owner and acceptance criteria.",validation:"Verified in common rules and functional requirements",files:"reports/x-lab-ui-ux-common-requirements.md"},
  {id:"FR-042",priority:"P0",module:"Demand management",requirement:"Requirement overview table / 需求总览表",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Ready",owner:"Product + Design",scope:"Requirement page, docs, Notion sync",acceptance:"Page shows all collected requirements in one table with filters, sortable headers, statistics, VOC, dates and validation fields.",validation:"Source verified",files:"requirements-board.html"},
  {id:"FR-043",priority:"P0",module:"Documentation governance",requirement:"Markdown uniqueness and sync gate / Markdown 文档唯一性与同步门禁",vocIds:["VOC-023"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Active",owner:"Content + Product",scope:"All Markdown documents, Notion archive",acceptance:"One bilingual source document per type with change log and Notion sync.",validation:"Verified in common rules and weekly sync automation",files:"reports/x-lab-ui-ux-common-requirements.md"},
  {id:"FR-044",priority:"P0",module:"Demand management",requirement:"VOC list and requirement linkage / VOC 清单与需求关联",vocIds:["VOC-019","VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Ready",owner:"Product + Design",scope:"VOC list, requirement overview, shared data source",acceptance:"VOC list contains structured VOC IDs, source, observed date, persona, severity, confidence, status and linked requirement IDs; requirement table links each VOC ID back to the VOC list.",validation:"Source verified. Browser visual QA pending",files:"voc-list.html, requirements-board.html, xlab-data.js, app.js"},
  {id:"FR-045",priority:"P0",module:"Demand management",requirement:"Collapsible left-side management menu / 可收拢左侧管理菜单",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Ready",owner:"Product + Design",scope:"Requirement overview, VOC list, management navigation",acceptance:"Requirement and VOC management pages place navigation in a left sidebar; topbar keeps only brand, page title and collapse control; sidebar can collapse and remembers state; mobile layout remains usable.",validation:"Source verified. Browser visual QA pending",files:"requirements-board.html, voc-list.html, app.js, styles.css, xlab-data.js"},
  {id:"FR-046",priority:"P0",module:"Demand management",requirement:"Compact inline filter toolbar / 紧凑同排筛选工具条",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Ready",owner:"Product + Design",scope:"Requirement overview and VOC list filter toolbar",acceptance:"Search, filter controls and reset action stay on one row on desktop; reset button is compact and visually subordinate to primary table controls; mobile can stack for usability.",validation:"Source verified. Browser visual QA pending",files:"styles.css, requirements-board.html, voc-list.html, xlab-data.js"},
  {id:"FR-047",priority:"P0",module:"Demand management",requirement:"Sidebar-top collapse control and short labels / 侧栏顶部收拢控制与短标签",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Ready",owner:"Product + Design",scope:"Requirement overview and VOC list sidebar navigation",acceptance:"Collapse/expand control sits above the left menu; expanded sidebar shows full labels; collapsed sidebar shows only one English word per menu item; mobile keeps full menu labels.",validation:"Source verified. Browser visual QA pending",files:"requirements-board.html, voc-list.html, app.js, styles.css, xlab-data.js"},
  {id:"FR-048",priority:"P0",module:"Demand management",requirement:"VOC-to-requirement scored review gate / VOC 转需求评分评审门禁",vocIds:["VOC-019","VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Ready",owner:"Product",scope:"VOC list, requirement intake, demand conversion workflow",acceptance:"VOC records show review dimensions for evidence, impact, reach, urgency and strategic fit; total score is calculated out of 100; only VOC scoring above 60 is marked Pass and allowed to enter the requirement list; VOC scoring 60 or below remains in review.",validation:"Source verified. Browser visual QA pending",files:"voc-list.html, xlab-data.js, app.js, styles.css, reports/x-lab-functional-requirements-bilingual-2026-06-06.md"},
  {id:"FR-049",priority:"P0",module:"Demand management",requirement:"Boss requirement classification / Boss 需求分类",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Ready",owner:"Product",scope:"Requirement overview, VOC list, prioritization rules",acceptance:"VOC and requirement tables show a demand class field; user directive records are labeled Boss requirement; Boss requirement is treated as the highest-priority category and sorts before other demand classes.",validation:"Source verified. Browser visual QA pending",files:"requirements-board.html, voc-list.html, xlab-data.js, app.js, styles.css, reports/x-lab-functional-requirements-bilingual-2026-06-06.md"},
  {id:"FR-050",priority:"P0",module:"Demand management",requirement:"Icon-only sidebar collapse control / 纯图标侧栏收拢控制",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-06",status:"Ready",owner:"Product + Design",scope:"Requirement overview and VOC list sidebar navigation",acceptance:"Sidebar collapse and expand control is shown as a compact icon-only button at the top-left of the sidebar; visible Collapse/Expand text is removed; aria-label and title keep the action accessible; collapsed and expanded states use opposite chevron directions.",validation:"Source verified. Browser visual QA pending",files:"requirements-board.html, voc-list.html, app.js, styles.css, xlab-data.js, reports/x-lab-functional-requirements-bilingual-2026-06-06.md"},
  {id:"FR-051",priority:"P0",module:"Demand management",requirement:"Monthly MVP planning and deadline governance / 月度 MVP 规划与 deadline 治理",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-30",status:"Ready",owner:"Product",scope:"Requirement overview, monthly roadmap, MVP delivery governance",acceptance:"All requirements show development month, monthly deadline and MVP phase; development is planned and completed by month; MVP Core is delivered first, MVP Extension follows, and Phase 2 waits behind the MVP scope.",validation:"Source verified. Browser visual QA pending",files:"requirements-board.html, xlab-data.js, app.js, styles.css, reports/x-lab-functional-requirements-bilingual-2026-06-06.md"},
  {id:"FR-052",priority:"P0",module:"Design governance",requirement:"Visual design system page and sync log / 可视化设计系统页面与同步日志",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-30",status:"Ready",owner:"Design + Product",scope:"Design system, management menu, design.md sync, edit log",acceptance:"A visual design system page is available from the left management menu; it summarizes design.md tokens, typography, UI specifications, component rules and governance; it includes an edit log; design.md records the visual page and must stay synchronized periodically.",validation:"Source verified. Browser visual QA pending",files:"design-system.html, design.md, requirements-board.html, voc-list.html, styles.css, xlab-data.js, reports/x-lab-functional-requirements-bilingual-2026-06-06.md"},
  {id:"FR-053",priority:"P0",module:"Demand management",requirement:"Notion requirement database sync / Notion 需求数据库同步",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-30",status:"Ready",owner:"Product",scope:"Notion requirement database, requirement overview, xlab-data display cache",acceptance:"Create a Notion requirement database with fields matching the local requirement overview; sync all current requirements from xlab-data.js; verify synced records by searchable requirement IDs; keep Notion as collaborative archive and local xlab-data.js as the display cache until two-way sync is implemented.",validation:"Source verified. Notion database sync verified",files:"xlab-data.js, requirements-board.html, reports/x-lab-functional-requirements-bilingual-2026-06-06.md, Notion database"},
  {id:"FR-054",priority:"P0",module:"Demand management",requirement:"Notion VOC database sync / Notion VOC 数据库同步",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-30",status:"Ready",owner:"Product",scope:"Notion VOC database, VOC list, VOC review gate, xlab-data display cache",acceptance:"Create a Notion VOC database with fields matching the local VOC list and review gate; sync all current VOC records from xlab-data.js; include category, theme, summary, persona, source, observed date, sentiment, severity, confidence, owner, status, linked requirements, evidence, scoring dimensions, total score and gate decision; verify synced records by searchable VOC IDs.",validation:"Source verified. Notion VOC database sync verified",files:"xlab-data.js, voc-list.html, reports/x-lab-functional-requirements-bilingual-2026-06-06.md, Notion VOC database"},
  {id:"FR-055",priority:"P0",module:"Demand management",requirement:"Bilingual VOC table data / VOC 表格数据双语化",vocIds:["VOC-022"],requestDate:"2026-06-06",plannedDate:"2026-06-30",status:"Ready",owner:"Product + Content",scope:"VOC list, xlab-data display cache, Notion VOC sync",acceptance:"VOC table records must display core readable fields in Chinese and English, including category, theme, summary, persona and source; search and filters must continue to work after bilingual data is applied; Notion VOC records should be updated in the next sync cycle.",validation:"Source verified. Local data validation passed",files:"xlab-data.js, voc-list.html, reports/x-lab-functional-requirements-bilingual-2026-06-06.md, Notion VOC database"}
];
